# Generated by Django 3.1.1 on 2020-09-16 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '김민혁 커뮤니티 사용자', 'verbose_name_plural': '김민혁 커뮤니티 사용자'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
